baseURL = 'https://dertev.de/'
languageCode = 'de-de'
title = 'Tim'
theme = "m10c"

[params]
description = "Hey! 👋 I'm Tim and I like to code in Clojure(Script)."
avatar = "https://github.com/DerTev.png"
favicon = "https://github.com/DerTev.png"

[[params.social]]
  icon = "github"
  name = "My GitHub"
  url = "https://github.com/DerTev"

[[params.social]]
  icon = "message-square"
  name = "My Matrix"
  url = "https://matrix.to/#/@tim:dertev.de"

[[menu.main]]
  identifier = "showcase"
  name = "Things I've made"
  url = "/showcase/"
  